//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolidsoftReply.Esb.Libraries.Uddi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolidsoftReply.Esb.Libraries.Uddi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to read an app setting value for {0} from the configuration file failed.
        ///{1}.
        /// </summary>
        internal static string AppSettingReadFailed {
            get {
                return ResourceManager.GetString("AppSettingReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to log a message to the {0}.  It was logged to the Application source instead.
        ///
        ///The error message when attempting to log was:
        ///
        ///{1}.
        /// </summary>
        internal static string ArgumentExceptionLoggedToApplication {
            get {
                return ResourceManager.GetString("ArgumentExceptionLoggedToApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert {0} to a decimal due to invalid format.  The default value {1} will be returned.
        ///{2}.
        /// </summary>
        internal static string ConversionToDecimalFailedInvalidFormat {
            get {
                return ResourceManager.GetString("ConversionToDecimalFailedInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert {0} to a decimal due to an overflow error.  The default value {1} will be returned.
        ///{2}.
        /// </summary>
        internal static string ConversionToDecimalFailedOverflow {
            get {
                return ResourceManager.GetString("ConversionToDecimalFailedOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine: {0}
        ///Processor count: {1}
        ///User: {2}\{3}
        ///OS version: {4} [{5}]
        ///Process: {6} [{7}] started at {8} and run for {9}
        ///PID: {10}
        ///Thread ID: {11}
        ///Terminal Services session: {12}
        ///.NET RTE version: {13}
        ///Memory: virtual = {14} bytes; working set = {15} bytes
        ///Stack trace:
        ///{16}.
        /// </summary>
        internal static string EnvironmentInfoTemplate {
            get {
                return ResourceManager.GetString("EnvironmentInfoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solidsoft Reply ESB UDDI inquiry services have been successfully initialised.  The default UDDI inquiry URL is {0}..
        /// </summary>
        internal static string InquiryInitialised {
            get {
                return ResourceManager.GetString("InquiryInitialised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solidsoft Reply ESB UDDI inquiry services are initialising..
        /// </summary>
        internal static string InquiryStartup {
            get {
                return ResourceManager.GetString("InquiryStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more invalid UDDI directory inquiry sites were returned from Active Directory.
        ///
        ///{0}.
        /// </summary>
        internal static string InvalidUddiSitesFoundInAd {
            get {
                return ResourceManager.GetString("InvalidUddiSitesFoundInAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following URI is invalid: {0}.
        /// </summary>
        internal static string InvalidUri {
            get {
                return ResourceManager.GetString("InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invalid URI {0} will be replaced by: {1}.
        /// </summary>
        internal static string InvalidUriWillBeReplaced {
            get {
                return ResourceManager.GetString("InvalidUriWillBeReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solidsoft Reply ESB UDDI.
        /// </summary>
        internal static string SolidsoftEsbUddiSource {
            get {
                return ResourceManager.GetString("SolidsoftEsbUddiSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SOAP fault occurred when invoking a UDDI service..
        /// </summary>
        internal static string Uddi {
            get {
                return ResourceManager.GetString("Uddi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null UDDI connection was passed when trying to invoke a UDDI service..
        /// </summary>
        internal static string UddiConnectionIsNull {
            get {
                return ResourceManager.GetString("UddiConnectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}{2}
        ///Request Type: {3}
        ///Authentication Type: {4}
        ///Directory Description: {5}
        ///Inquiry URL: {6}
        ///Publish URL: {7}
        ///Extensions URL: {8}
        ///{0}.
        /// </summary>
        internal static string UddiErrorTemplate {
            get {
                return ResourceManager.GetString("UddiErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid key value was passed when trying to invoke a UDDI service..
        /// </summary>
        internal static string UddiInvalid {
            get {
                return ResourceManager.GetString("UddiInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null site location or Inquiry URL was passed when trying to invoke a UDDI service..
        /// </summary>
        internal static string UddiInvalidSiteError {
            get {
                return ResourceManager.GetString("UddiInvalidSiteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A UDDI site directory cache entry has been unexpectedly removed.  The reason given is {0}.
        /// </summary>
        internal static string UddiSiteUnexpectedlyRemovedFromCache {
            get {
                return ResourceManager.GetString("UddiSiteUnexpectedlyRemovedFromCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred when invoking a UDDI service. .
        /// </summary>
        internal static string UddiUnexpected {
            get {
                return ResourceManager.GetString("UddiUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred when invoking a UDDI service..
        /// </summary>
        internal static string UddiUnknown {
            get {
                return ResourceManager.GetString("UddiUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown message type was passed when trying to invoke a UDDI service..
        /// </summary>
        internal static string UddiUnknownMessageType {
            get {
                return ResourceManager.GetString("UddiUnknownMessageType", resourceCulture);
            }
        }
    }
}
