//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolidsoftReply.Esb.Libraries.Resolution.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolidsoftReply.Esb.Libraries.Resolution.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BAM.BufferedConnectionString.
        /// </summary>
        internal static string AppSettingEsbBamBufferedConnectionString {
            get {
                return ResourceManager.GetString("AppSettingEsbBamBufferedConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BAM.DefaultTrackpointPolicyName.
        /// </summary>
        internal static string AppSettingEsbBamDefaultTrackpointPolicy {
            get {
                return ResourceManager.GetString("AppSettingEsbBamDefaultTrackpointPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BAM.DefaultTrackpointPolicyVersion.
        /// </summary>
        internal static string AppSettingEsbBamDefaultTrackpointPolicyVersion {
            get {
                return ResourceManager.GetString("AppSettingEsbBamDefaultTrackpointPolicyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BAM.DirectConnectionString.
        /// </summary>
        internal static string AppSettingEsbBamDirectConnectionString {
            get {
                return ResourceManager.GetString("AppSettingEsbBamDirectConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BAM.FlushThreshold.
        /// </summary>
        internal static string AppSettingEsbBamFlushThreshold {
            get {
                return ResourceManager.GetString("AppSettingEsbBamFlushThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BAM.IsBuffered.
        /// </summary>
        internal static string AppSettingEsbBamIsBuffered {
            get {
                return ResourceManager.GetString("AppSettingEsbBamIsBuffered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.DirectivesCacheExpiration.
        /// </summary>
        internal static string AppSettingEsbCacheExpiration {
            get {
                return ResourceManager.GetString("AppSettingEsbCacheExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.DefaultPolicyName.
        /// </summary>
        internal static string AppSettingEsbDefaultPolicy {
            get {
                return ResourceManager.GetString("AppSettingEsbDefaultPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.ServiceEndPoint.
        /// </summary>
        internal static string AppSettingEsbServiceEndPoint {
            get {
                return ResourceManager.GetString("AppSettingEsbServiceEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BRE.PolicyTester.
        /// </summary>
        internal static string AppSettingsEsbBrePolicyTester {
            get {
                return ResourceManager.GetString("AppSettingsEsbBrePolicyTester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BRE.Trace.
        /// </summary>
        internal static string AppSettingsEsbBreTrace {
            get {
                return ResourceManager.GetString("AppSettingsEsbBreTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BRE.TraceFileLocation.
        /// </summary>
        internal static string AppSettingsEsbBreTraceFileLocation {
            get {
                return ResourceManager.GetString("AppSettingsEsbBreTraceFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAMActivity_{0}_{1}_{2}{3}.
        /// </summary>
        internal static string BamActivityKey {
            get {
                return ResourceManager.GetString("BamActivityKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://solidsoftreply.com/schemas/webservices/esbresolutionservice/2015/05.
        /// </summary>
        internal static string DictionaryNamespace {
            get {
                return ResourceManager.GetString("DictionaryNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAM activity name is null or empty..
        /// </summary>
        internal static string ExceptionBamActivityNameInvalid {
            get {
                return ResourceManager.GetString("ExceptionBamActivityNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAM trackpoint policy cannot be determined..
        /// </summary>
        internal static string ExceptionBamTrackpointPolicyUndetermined {
            get {
                return ResourceManager.GetString("ExceptionBamTrackpointPolicyUndetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAM Trackpoint policy version is invalid.  Specified version is {0}..
        /// </summary>
        internal static string ExceptionBamTrackpointPolicyVersionInvalid {
            get {
                return ResourceManager.GetString("ExceptionBamTrackpointPolicyVersionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be de-serialized.   The &lt;Key&gt; element is invalid.  It must contain &lt;string&gt;keyValue&lt;/string&gt;.
        /// </summary>
        internal static string ExceptionDeserializationInvalidKeyElement {
            get {
                return ResourceManager.GetString("ExceptionDeserializationInvalidKeyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be de-serialised.   No &lt;{1}&gt; element was found..
        /// </summary>
        internal static string ExceptionDeserializationNoElement {
            get {
                return ResourceManager.GetString("ExceptionDeserializationNoElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element asked is not on the actual list..
        /// </summary>
        internal static string ExceptionElementNotOnList {
            get {
                return ResourceManager.GetString("ExceptionElementNotOnList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB policy cannot be determined.  Add an AppSetting to the configuration file called &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionEsbPolicyUndetermined {
            get {
                return ResourceManager.GetString("ExceptionEsbPolicyUndetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialization failure: info cannot be null on {0}..
        /// </summary>
        internal static string ExceptionInfoNull {
            get {
                return ResourceManager.GetString("ExceptionInfoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAM interception failure.  The data passed to the XPath data extractor is not XML..
        /// </summary>
        internal static string ExceptionInterceptionFailedNotXml {
            get {
                return ResourceManager.GetString("ExceptionInterceptionFailedNotXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAM interception failure.  The extraction information passed to the XPath data extractor is not a valid XPath string.   Check the  resolver&apos;s BAM policy.  XPath: {0}.
        /// </summary>
        internal static string ExceptionInterceptionFailedNotXPath {
            get {
                return ResourceManager.GetString("ExceptionInterceptionFailedNotXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BAM extraction string contains a macro with invalid brace nesting.  Extraction string is {0}.
        /// </summary>
        internal static string ExceptionInterceptionInvalidParenthesis {
            get {
                return ResourceManager.GetString("ExceptionInterceptionInvalidParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to obtain a BAM interceptor for activity {0} while processing resolver directive {1}..
        /// </summary>
        internal static string ExceptionInterceptorNotObtained {
            get {
                return ResourceManager.GetString("ExceptionInterceptorNotObtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An ESB Resolver directive is invalid or does not exist.  Check that the directive name exists in the policy..
        /// </summary>
        internal static string ExceptionInvalidDirective {
            get {
                return ResourceManager.GetString("ExceptionInvalidDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key not found in cache.
        /// </summary>
        internal static string ExceptionKeyNotFound {
            get {
                return ResourceManager.GetString("ExceptionKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map class &apos;{0}&apos; is not valid and cannot be instantiated.
        /// </summary>
        internal static string ExceptionMapClassInvalid {
            get {
                return ResourceManager.GetString("ExceptionMapClassInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map has an invalid strong name.  Full name is {0}.
        /// </summary>
        internal static string ExceptionMapFullName {
            get {
                return ResourceManager.GetString("ExceptionMapFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB Resolver directive {0} indicates that BAM interception is required, but no activity has been specified..
        /// </summary>
        internal static string ExceptionNoActivity {
            get {
                return ResourceManager.GetString("ExceptionNoActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB Resolver directive {0} indicates that BAM interception is required, but no activity step has been specified..
        /// </summary>
        internal static string ExceptionNoActivityStep {
            get {
                return ResourceManager.GetString("ExceptionNoActivityStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the Bam Activity object.
        /// </summary>
        internal static string ExceptionNoBamActivity {
            get {
                return ResourceManager.GetString("ExceptionNoBamActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ESB policy defined..
        /// </summary>
        internal static string ExceptionNoPolicyDefined {
            get {
                return ResourceManager.GetString("ExceptionNoPolicyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No TrackPoints from the BRE.
        /// </summary>
        internal static string ExceptionNoTrackpoints {
            get {
                return ResourceManager.GetString("ExceptionNoTrackpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object is not constructed properly..
        /// </summary>
        internal static string ExceptionObjectMisconstructed {
            get {
                return ResourceManager.GetString("ExceptionObjectMisconstructed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BAM step has attempted to access a missing property named {0}..
        /// </summary>
        internal static string ExceptionPropertyNotAvailable {
            get {
                return ResourceManager.GetString("ExceptionPropertyNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML reader passed to the {0} method is null..
        /// </summary>
        internal static string ExceptionReaderIsNull {
            get {
                return ResourceManager.GetString("ExceptionReaderIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find XSD schema in assembly resources..
        /// </summary>
        internal static string ExceptionSchemaResourceNotFound {
            get {
                return ResourceManager.GetString("ExceptionSchemaResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML schema set passed to the {0} method is null..
        /// </summary>
        internal static string ExceptionSchemaSetIsNull {
            get {
                return ResourceManager.GetString("ExceptionSchemaSetIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be serialized.   See inner exception..
        /// </summary>
        internal static string ExceptionSerialization {
            get {
                return ResourceManager.GetString("ExceptionSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred when calling {0}.  See inner exception..
        /// </summary>
        internal static string ExceptionUnexpectedError {
            get {
                return ResourceManager.GetString("ExceptionUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null..
        /// </summary>
        internal static string ExceptionValueIsNull {
            get {
                return ResourceManager.GetString("ExceptionValueIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML writer passed to the {0} method is null..
        /// </summary>
        internal static string ExceptionWriterIsNull {
            get {
                return ResourceManager.GetString("ExceptionWriterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BAM macro defines {0} parameters, but only {1} values have been provided..
        /// </summary>
        internal static string ExceptionWrongNumberOfMacroParameters {
            get {
                return ResourceManager.GetString("ExceptionWrongNumberOfMacroParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML document/message could not be transformed for resolver directive {0}.  Message is null..
        /// </summary>
        internal static string ExceptionXmlTransformationFailedOnNull {
            get {
                return ResourceManager.GetString("ExceptionXmlTransformationFailedOnNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;!{)(?:{)(?:(?&apos;invalidParenthesis&apos;(?:{){2})*)(?&apos;macro&apos;(?:now|date|day|dayofweek|dayofyear|hour|millisecond|minute|month|second|ticks|timeofday|today|utcnow|year|guid|property))(?::(?&apos;format&apos;[^}]+))?(?&lt;!})(?:})(?:(?&apos;-invalidParenthesis&apos;(?:}){2})*).
        /// </summary>
        internal static string MacroExpression {
            get {
                return ResourceManager.GetString("MacroExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/aggschema.
        /// </summary>
        internal static string UriAggSchema {
            get {
                return ResourceManager.GetString("UriAggSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolidsoftReply.Esb.Libraries.Resolution.Resources.DictionarySchema.xsd.
        /// </summary>
        internal static string XmlFileDictionarySchema {
            get {
                return ResourceManager.GetString("XmlFileDictionarySchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //ExtensionObjects/ExtensionObject.
        /// </summary>
        internal static string XPathExtensionObject {
            get {
                return ResourceManager.GetString("XPathExtensionObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolidsoftReply.Esb.Libraries.Resolution.Dictionaries.Resources.BtsPropertiesSchema.xsd.
        /// </summary>
        internal static string XsdBtsPropertiesSchemaFile {
            get {
                return ResourceManager.GetString("XsdBtsPropertiesSchemaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolidsoftReply.Esb.Libraries.Resolution.Dictionaries.Resources..DictionarySchema.xsd.
        /// </summary>
        internal static string XsdDictionarySchemaFile {
            get {
                return ResourceManager.GetString("XsdDictionarySchemaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolidsoftReply.Esb.Libraries.Resolution.Dictionaries.Resources.DirectivesSchema.xsd.
        /// </summary>
        internal static string XsdDirectiveSchemaFile {
            get {
                return ResourceManager.GetString("XsdDirectiveSchemaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolidsoftReply.Esb.Libraries.Resolution.Dictionaries.Resources.DirectivesSchemaProperties.xsd.
        /// </summary>
        internal static string XsdDirectiveSchemaPropertiesFile {
            get {
                return ResourceManager.GetString("XsdDirectiveSchemaPropertiesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolidsoftReply.Esb.Libraries.Resolution.Dictionaries.Resources.ParametersSchema.xsd.
        /// </summary>
        internal static string XsdParameterSchemaFile {
            get {
                return ResourceManager.GetString("XsdParameterSchemaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolidsoftReply.Esb.Libraries.Resolution.Dictionaries.Resources.PropertiesSchema.xsd.
        /// </summary>
        internal static string XsdPropertiesSchemaFile {
            get {
                return ResourceManager.GetString("XsdPropertiesSchemaFile", resourceCulture);
            }
        }
    }
}
