//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolidsoftReply.Esb.Libraries.BizTalk.PipelineComponents.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolidsoftReply.Esb.Libraries.BizTalk.PipelineComponents.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BRE.PolicyTester.
        /// </summary>
        internal static string AppSettingsEsbBrePolicyTester {
            get {
                return ResourceManager.GetString("AppSettingsEsbBrePolicyTester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BRE.Trace.
        /// </summary>
        internal static string AppSettingsEsbBreTrace {
            get {
                return ResourceManager.GetString("AppSettingsEsbBreTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BRE.TraceFileLocation.
        /// </summary>
        internal static string AppSettingsEsbBreTraceFileLocation {
            get {
                return ResourceManager.GetString("AppSettingsEsbBreTraceFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.DefaultPolicy.
        /// </summary>
        internal static string AppSettingsEsbDefaultPolicy {
            get {
                return ResourceManager.GetString("AppSettingsEsbDefaultPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server={0};Database={1};Integrated Security=SSPI.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether to allow messages that do not have a recognized schema to be passed through the disassembler..
        /// </summary>
        internal static string DescAllowUnrecognizedMessage {
            get {
                return ResourceManager.GetString("DescAllowUnrecognizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An identifier for a binding access point.   The identifier should  be in the form of a URL.   This may be used when the endpoint URL is known, but other resolution is required, or as a &apos;virtual&apos; URL.  This is based on UDDI..
        /// </summary>
        internal static string DescBindingAccessPoint {
            get {
                return ResourceManager.GetString("DescBindingAccessPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type (scheme) of URL for the target service.   This is based on UDDI..
        /// </summary>
        internal static string DescBindingUrlType {
            get {
                return ResourceManager.GetString("DescBindingUrlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An XPath that addresses the element that contains the body of the message.    If blank, the conceptual &apos;Root&apos; node (parent of the Document Element) is used..
        /// </summary>
        internal static string DescBodyContainerXPath {
            get {
                return ResourceManager.GetString("DescBodyContainerXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the schema to be applied to the document..
        /// </summary>
        internal static string DescDocumentSpecName {
            get {
                return ResourceManager.GetString("DescDocumentSpecName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the schema(s) to be applied to the document..
        /// </summary>
        internal static string DescDocumentSpecNames {
            get {
                return ResourceManager.GetString("DescDocumentSpecNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the schema(s) to be applied to the envelope..
        /// </summary>
        internal static string DescEnvelopeSpecNames {
            get {
                return ResourceManager.GetString("DescEnvelopeSpecNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat file disassembler component.
        /// </summary>
        internal static string DescFFDasmDesription {
            get {
                return ResourceManager.GetString("DescFFDasmDesription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the name of the component..
        /// </summary>
        internal static string DescFFDasmName {
            get {
                return ResourceManager.GetString("DescFFDasmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version description.
        /// </summary>
        internal static string DescFFDasmVersion {
            get {
                return ResourceManager.GetString("DescFFDasmVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the schema to be applied to the header..
        /// </summary>
        internal static string DescHeaderSpecName {
            get {
                return ResourceManager.GetString("DescHeaderSpecName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction of message..
        /// </summary>
        internal static string DescMessageDirection {
            get {
                return ResourceManager.GetString("DescMessageDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A role specifier for the message.   Equivalent to messageLabel in WSDL 2.0.
        /// </summary>
        internal static string DescMessageRole {
            get {
                return ResourceManager.GetString("DescMessageRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of message.   In a BizTalk Server context, this should generally be equivalent to the BTS.MessageType property..
        /// </summary>
        internal static string DescMessageType {
            get {
                return ResourceManager.GetString("DescMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the service operation to be invoked..
        /// </summary>
        internal static string DescOperationName {
            get {
                return ResourceManager.GetString("DescOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the rule policy to be executed..
        /// </summary>
        internal static string DescPolicy {
            get {
                return ResourceManager.GetString("DescPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of rule policy to be executed. If empty, the latest version will be executed..
        /// </summary>
        internal static string DescPolicyVersion {
            get {
                return ResourceManager.GetString("DescPolicyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the header document will be preserved..
        /// </summary>
        internal static string DescPreserveHeader {
            get {
                return ResourceManager.GetString("DescPreserveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human-friendly name of service provider.   This is equivalent to the business entity name in UDDI..
        /// </summary>
        internal static string DescProviderName {
            get {
                return ResourceManager.GetString("DescProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether the disassembler will attempt to recover from errors during interchange processing..
        /// </summary>
        internal static string DescRecoverableInterchangeProcessing {
            get {
                return ResourceManager.GetString("DescRecoverableInterchangeProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human-friendly name for target service.   This is equivalent to the business service name in UDDI..
        /// </summary>
        internal static string DescServiceName {
            get {
                return ResourceManager.GetString("DescServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the BAM event stream will be synchronized with the pipeline context.  When set to true, this setting overrides event stream buffering defined in directives..
        /// </summary>
        internal static string DescSynchronizeBam {
            get {
                return ResourceManager.GetString("DescSynchronizeBam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the schema to be applied to the trailer..
        /// </summary>
        internal static string DescTrailerSpecName {
            get {
                return ResourceManager.GetString("DescTrailerSpecName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether to validate the envelope and document structures of incoming messages..
        /// </summary>
        internal static string DescValidate {
            get {
                return ResourceManager.GetString("DescValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether to validate the header, the trailer and the document structures of incoming messages..
        /// </summary>
        internal static string DescValidateDocumentStructure {
            get {
                return ResourceManager.GetString("DescValidateDocumentStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml disassembler component with ESB governance..
        /// </summary>
        internal static string DescXmlDasmDesription {
            get {
                return ResourceManager.GetString("DescXmlDasmDesription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the name of the component..
        /// </summary>
        internal static string DescXmlDasmName {
            get {
                return ResourceManager.GetString("DescXmlDasmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version description.
        /// </summary>
        internal static string DescXmlDasmVersion {
            get {
                return ResourceManager.GetString("DescXmlDasmVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DisassemblerIcon {
            get {
                object obj = ResourceManager.GetObject("DisassemblerIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the parameters in the registry to connect to the business rule store.
        /// </summary>
        internal static string ExceptionNoConnectionParameters {
            get {
                return ResourceManager.GetString("ExceptionNoConnectionParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a valid message part.  The XML content of the body part is invalid, or the part does not exist:\r\n\r\n{0}.
        /// </summary>
        internal static string ExceptionNoValidMessagePart {
            get {
                return ResourceManager.GetString("ExceptionNoValidMessagePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB policy cannot be determined.  Add an AppSetting to the config file called &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionPolicyUndetermined {
            get {
                return ResourceManager.GetString("ExceptionPolicyUndetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ruleset &apos;{0}&apos; version {1}.{2} specified is not in the rule store..
        /// </summary>
        internal static string ExceptionRsNotInStore {
            get {
                return ResourceManager.GetString("ExceptionRsNotInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5EEEF32A-5601-4D8D-B2DA-D939484F08E7.
        /// </summary>
        internal static string FlatFileDasmGovernanceComponentClassId {
            get {
                return ResourceManager.GetString("FlatFileDasmGovernanceComponentClassId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies ESB governance in the context of a Fat File Disassembler within a BizTalk Server pipeline..
        /// </summary>
        internal static string FlatFileDasmGovernanceComponentDescription {
            get {
                return ResourceManager.GetString("FlatFileDasmGovernanceComponentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat file disassembler with ESB Governance.
        /// </summary>
        internal static string FlatFileDasmGovernanceComponentName {
            get {
                return ResourceManager.GetString("FlatFileDasmGovernanceComponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 59CFD96B-20EE-40ad-BFD0-319B59A0DDBC.
        /// </summary>
        internal static string GovernanceComponentClassId {
            get {
                return ResourceManager.GetString("GovernanceComponentClassId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies ESB governance within a BizTalk Server pipeline..
        /// </summary>
        internal static string GovernanceComponentDescription {
            get {
                return ResourceManager.GetString("GovernanceComponentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB Governance.
        /// </summary>
        internal static string GovernanceComponentName {
            get {
                return ResourceManager.GetString("GovernanceComponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string PeopFFDasmVersion {
            get {
                return ResourceManager.GetString("PeopFFDasmVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow unrecognized message.
        /// </summary>
        internal static string PropAllowUnrecognizedMessage {
            get {
                return ResourceManager.GetString("PropAllowUnrecognizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding access point.
        /// </summary>
        internal static string PropBindingAccessPoint {
            get {
                return ResourceManager.GetString("PropBindingAccessPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding URL type.
        /// </summary>
        internal static string PropBindingUrlType {
            get {
                return ResourceManager.GetString("PropBindingUrlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body container XPath.
        /// </summary>
        internal static string PropBodyContainerXPath {
            get {
                return ResourceManager.GetString("PropBodyContainerXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document schema.
        /// </summary>
        internal static string PropDocumentSpecName {
            get {
                return ResourceManager.GetString("PropDocumentSpecName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document schemas.
        /// </summary>
        internal static string PropDocumentSpecNames {
            get {
                return ResourceManager.GetString("PropDocumentSpecNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope schemas.
        /// </summary>
        internal static string PropEnvelopeSpecNames {
            get {
                return ResourceManager.GetString("PropEnvelopeSpecNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desription.
        /// </summary>
        internal static string PropFFDasmDesription {
            get {
                return ResourceManager.GetString("PropFFDasmDesription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PropFFDasmName {
            get {
                return ResourceManager.GetString("PropFFDasmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header schema.
        /// </summary>
        internal static string PropHeaderSpecName {
            get {
                return ResourceManager.GetString("PropHeaderSpecName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message direction.
        /// </summary>
        internal static string PropMessageDirection {
            get {
                return ResourceManager.GetString("PropMessageDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message role.
        /// </summary>
        internal static string PropMessageRole {
            get {
                return ResourceManager.GetString("PropMessageRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type.
        /// </summary>
        internal static string PropMessageType {
            get {
                return ResourceManager.GetString("PropMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation name.
        /// </summary>
        internal static string PropOperationName {
            get {
                return ResourceManager.GetString("PropOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        internal static string PropPolicy {
            get {
                return ResourceManager.GetString("PropPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy version.
        /// </summary>
        internal static string PropPolicyVersion {
            get {
                return ResourceManager.GetString("PropPolicyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve header.
        /// </summary>
        internal static string PropPreserveHeader {
            get {
                return ResourceManager.GetString("PropPreserveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider name.
        /// </summary>
        internal static string PropProviderName {
            get {
                return ResourceManager.GetString("PropProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recoverable interchange processing.
        /// </summary>
        internal static string PropRecoverableInterchangeProcessing {
            get {
                return ResourceManager.GetString("PropRecoverableInterchangeProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name.
        /// </summary>
        internal static string PropServiceName {
            get {
                return ResourceManager.GetString("PropServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize BAM.
        /// </summary>
        internal static string PropSynchronizeBam {
            get {
                return ResourceManager.GetString("PropSynchronizeBam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailer schema.
        /// </summary>
        internal static string PropTrailerSpecName {
            get {
                return ResourceManager.GetString("PropTrailerSpecName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate document structure.
        /// </summary>
        internal static string PropValidate {
            get {
                return ResourceManager.GetString("PropValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate document structure.
        /// </summary>
        internal static string PropValidateDocumentStructure {
            get {
                return ResourceManager.GetString("PropValidateDocumentStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming XML disassembler with ESB governance.
        /// </summary>
        internal static string PropXmlDasmDescription {
            get {
                return ResourceManager.GetString("PropXmlDasmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PropXmlDasmName {
            get {
                return ResourceManager.GetString("PropXmlDasmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string PropXmlDasmVersion {
            get {
                return ResourceManager.GetString("PropXmlDasmVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Microsoft\\BusinessRules\\3.0.
        /// </summary>
        internal static string RegKey {
            get {
                return ResourceManager.GetString("RegKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseName.
        /// </summary>
        internal static string RegKeyDatabaseName {
            get {
                return ResourceManager.GetString("RegKeyDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseServer.
        /// </summary>
        internal static string RegKeyDatabaseServer {
            get {
                return ResourceManager.GetString("RegKeyDatabaseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Wow6432Node\\Microsoft\\BusinessRules\\3.0.
        /// </summary>
        internal static string RegKeyWow6432 {
            get {
                return ResourceManager.GetString("RegKeyWow6432", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/system-properties.
        /// </summary>
        internal static string UriBtsSystemProperties {
            get {
                return ResourceManager.GetString("UriBtsSystemProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/xlangs-properties.
        /// </summary>
        internal static string UriMicrosoftBizTalkXLANGsBTXEngineProperties {
            get {
                return ResourceManager.GetString("UriMicrosoftBizTalkXLANGsBTXEngineProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/wse-properties.
        /// </summary>
        internal static string UriWseProperties {
            get {
                return ResourceManager.GetString("UriWseProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/BizTalk/2003/xmlnorm-properties.
        /// </summary>
        internal static string UriXmlNormProperties {
            get {
                return ResourceManager.GetString("UriXmlNormProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/2001/XMLSchema-instance.
        /// </summary>
        internal static string UriXsd {
            get {
                return ResourceManager.GetString("UriXsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DA2A8452-88E1-4C96-B5E7-8B04AABBFBF3.
        /// </summary>
        internal static string XmlDasmGovernanceComponentClassId {
            get {
                return ResourceManager.GetString("XmlDasmGovernanceComponentClassId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies ESB governance in the context of an XML Disassembler within a BizTalk Server pipeline..
        /// </summary>
        internal static string XmlDasmGovernanceComponentDescription {
            get {
                return ResourceManager.GetString("XmlDasmGovernanceComponentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML disassembler with ESB Governance.
        /// </summary>
        internal static string XmlDasmGovernanceComponentName {
            get {
                return ResourceManager.GetString("XmlDasmGovernanceComponentName", resourceCulture);
            }
        }
    }
}
