//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolidsoftReply.Esb.Libraries.BizTalk.Orchestration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolidsoftReply.Esb.Libraries.BizTalk.Orchestration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BRE.PolicyTester.
        /// </summary>
        internal static string AppSettingsEsbBrePolicyTester {
            get {
                return ResourceManager.GetString("AppSettingsEsbBrePolicyTester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BRE.Trace.
        /// </summary>
        internal static string AppSettingsEsbBreTrace {
            get {
                return ResourceManager.GetString("AppSettingsEsbBreTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BRE.TraceFileLocation.
        /// </summary>
        internal static string AppSettingsEsbBreTraceFileLocation {
            get {
                return ResourceManager.GetString("AppSettingsEsbBreTraceFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server={0};Database={1};Integrated Security=SSPI.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the parameters in the registry to connect to the business rule store.
        /// </summary>
        internal static string ExceptionNoConnectionParameters {
            get {
                return ResourceManager.GetString("ExceptionNoConnectionParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ruleset &apos;{0}&apos; version {1}.{2} specified is not in the rule store..
        /// </summary>
        internal static string ExceptionRsNotInStore {
            get {
                return ResourceManager.GetString("ExceptionRsNotInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Microsoft\\BusinessRules\\3.0.
        /// </summary>
        internal static string RegKey {
            get {
                return ResourceManager.GetString("RegKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseName.
        /// </summary>
        internal static string RegKeyDatabaseName {
            get {
                return ResourceManager.GetString("RegKeyDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseServer.
        /// </summary>
        internal static string RegKeyDatabaseServer {
            get {
                return ResourceManager.GetString("RegKeyDatabaseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\Wow6432Node\\Microsoft\\BusinessRules\\3.0.
        /// </summary>
        internal static string RegKeyWow6432 {
            get {
                return ResourceManager.GetString("RegKeyWow6432", resourceCulture);
            }
        }
    }
}
