//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolidsoftReply.Esb.Libraries.Facts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolidsoftReply.Esb.Libraries.Facts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BAM.BufferedConnectionString.
        /// </summary>
        internal static string AppSettingEsbBamBufferedConnectionString {
            get {
                return ResourceManager.GetString("AppSettingEsbBamBufferedConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BAM.DefaultTrackpointPolicyName.
        /// </summary>
        internal static string AppSettingEsbBamDefaultTrackpointPolicyName {
            get {
                return ResourceManager.GetString("AppSettingEsbBamDefaultTrackpointPolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BAM.DefaultTrackpointPolicyVersion.
        /// </summary>
        internal static string AppSettingEsbBamDefaultTrackpointPolicyVersion {
            get {
                return ResourceManager.GetString("AppSettingEsbBamDefaultTrackpointPolicyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BAM.DirectConnectionString.
        /// </summary>
        internal static string AppSettingEsbBamDirectConnectionString {
            get {
                return ResourceManager.GetString("AppSettingEsbBamDirectConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BAM.FlushThreshold.
        /// </summary>
        internal static string AppSettingEsbBamFlushThreshold {
            get {
                return ResourceManager.GetString("AppSettingEsbBamFlushThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.BAM.IsBuffered.
        /// </summary>
        internal static string AppSettingEsbBamIsBuffered {
            get {
                return ResourceManager.GetString("AppSettingEsbBamIsBuffered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.ErrorOnInvalid.
        /// </summary>
        internal static string AppSettingEsbErrorOnInvalid {
            get {
                return ResourceManager.GetString("AppSettingEsbErrorOnInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.ValidationPolicyName.
        /// </summary>
        internal static string AppSettingEsbValidationPolicyName {
            get {
                return ResourceManager.GetString("AppSettingEsbValidationPolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESB.ValidationPolicyVersion.
        /// </summary>
        internal static string AppSettingEsbValidationPolicyVersion {
            get {
                return ResourceManager.GetString("AppSettingEsbValidationPolicyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.BizTalk.GlobalPropertySchemas, Version=3.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
        /// </summary>
        internal static string AssemblyQNameMicrosoftBizTalkGlobalPropertySchemas {
            get {
                return ResourceManager.GetString("AssemblyQNameMicrosoftBizTalkGlobalPropertySchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://solidsoftreply.com/schemas/webservices/esbresolutionservice/2015/05.
        /// </summary>
        internal static string DictionaryNamespace {
            get {
                return ResourceManager.GetString("DictionaryNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode steps for a single BAM activity only.   Use multiple directives for multiple BAM steps..
        /// </summary>
        internal static string ExceptionBamActivity {
            get {
                return ResourceManager.GetString("ExceptionBamActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directive {0} can only manage a single BAM activity name.   Check the resolution policy.   If neccessary, create multiple directives to handle different activities..
        /// </summary>
        internal static string ExceptionBamActivityName {
            get {
                return ResourceManager.GetString("ExceptionBamActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directive {0} can only manage a single after-map step name for a single BAM activity.   Check the resolution policy.   If neccessary, create multiple directives to handle different steps..
        /// </summary>
        internal static string ExceptionBamAfterMapStepName {
            get {
                return ResourceManager.GetString("ExceptionBamAfterMapStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode a single BAM connection string only.   Use multiple directives for multiple BAM steps..
        /// </summary>
        internal static string ExceptionBamConnectionString {
            get {
                return ResourceManager.GetString("ExceptionBamConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode a single BAM flush threshold only.   Use multiple directives for multiple BAM steps..
        /// </summary>
        internal static string ExceptionBamFlushThreshold {
            get {
                return ResourceManager.GetString("ExceptionBamFlushThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BAM flush threshold in the {0} directive must be set to a value of 1 or greater..
        /// </summary>
        internal static string ExceptionBamFlushThresholdLt1 {
            get {
                return ResourceManager.GetString("ExceptionBamFlushThresholdLt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode a single BAM is-buffered flag only.   Use multiple directives for multiple BAM steps..
        /// </summary>
        internal static string ExceptionBamIsBufferedFlag {
            get {
                return ResourceManager.GetString("ExceptionBamIsBufferedFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode a single BAM post-transformation step only.   Use multiple directives for multiple BAM steps..
        /// </summary>
        internal static string ExceptionBamPostTransformationStep {
            get {
                return ResourceManager.GetString("ExceptionBamPostTransformationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} step in the {1} BAM activity can be configured with a single &apos;start&apos; tackpoint only.  This may be a &apos;start new&apos;, &apos;continue&apos; or &apos;extend&apos; trackpoint..
        /// </summary>
        internal static string ExceptionBamStart {
            get {
                return ResourceManager.GetString("ExceptionBamStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode a single BAM step only.   Use multiple directives for multiple BAM steps..
        /// </summary>
        internal static string ExceptionBamStep {
            get {
                return ResourceManager.GetString("ExceptionBamStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directive {0} can only manage a single step name for a single BAM activity.   Check the resolution policy.   If neccessary, create multiple directives to handle different steps..
        /// </summary>
        internal static string ExceptionBamStepName {
            get {
                return ResourceManager.GetString("ExceptionBamStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode a single BAM Trackpoint policy name only.   Use multiple directives for multiple BAM steps..
        /// </summary>
        internal static string ExceptionBamTrackpointPolicyName {
            get {
                return ResourceManager.GetString("ExceptionBamTrackpointPolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode a single BAM Trackpoint policy version only.   Use multiple directives for multiple BAM steps..
        /// </summary>
        internal static string ExceptionBamTrackpointPolicyVersion {
            get {
                return ResourceManager.GetString("ExceptionBamTrackpointPolicyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Trackpoint policy version set in directive {0} is an invalid version specifier.\r\n.
        /// </summary>
        internal static string ExceptionBamTrackpointPolicyVersionInvalid {
            get {
                return ResourceManager.GetString("ExceptionBamTrackpointPolicyVersionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be de-serialized.   The &lt;Key&gt; element is invalid.  It must contain &lt;string&gt;keyValue&lt;/string&gt;.
        /// </summary>
        internal static string ExceptionDeserializationInvalidKeyElement {
            get {
                return ResourceManager.GetString("ExceptionDeserializationInvalidKeyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be de-serialised.   No &lt;{1}&gt; element was found..
        /// </summary>
        internal static string ExceptionDeserializationNoElement {
            get {
                return ResourceManager.GetString("ExceptionDeserializationNoElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode a single endpoint URL only.   Use multiple directives for multiple endpoints..
        /// </summary>
        internal static string ExceptionEndPoint {
            get {
                return ResourceManager.GetString("ExceptionEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode a single endpoint configuration token only.   Use multiple directives for multiple endpoints..
        /// </summary>
        internal static string ExceptionEndPointConfiguration {
            get {
                return ResourceManager.GetString("ExceptionEndPointConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The endpoint URL set in directive {0} is an invalid URI.\r\n.
        /// </summary>
        internal static string ExceptionEndPointInvalidUri {
            get {
                return ResourceManager.GetString("ExceptionEndPointInvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode a single &apos;error-on-invalid&apos; flag only for a single validation rule set.   Use multiple directives for multiple validation rule sets..
        /// </summary>
        internal static string ExceptionErrorOnInvalidFlag {
            get {
                return ResourceManager.GetString("ExceptionErrorOnInvalidFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BAM after-map step extension name(s).  No after-map step has been defined in directive {0}.
        /// </summary>
        internal static string ExceptionInvalidBamAfterMapExtendedStepNoStepName {
            get {
                return ResourceManager.GetString("ExceptionInvalidBamAfterMapExtendedStepNoStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BAM connection string for directive {0} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidBamConnectionstring {
            get {
                return ResourceManager.GetString("ExceptionInvalidBamConnectionstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BAM step name provided for extension - {0}.
        /// </summary>
        internal static string ExceptionInvalidBamExtendedStepName {
            get {
                return ResourceManager.GetString("ExceptionInvalidBamExtendedStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BAM step extension name(s).  No step has been defined in directive {0}.
        /// </summary>
        internal static string ExceptionInvalidBamExtendedStepNoStepName {
            get {
                return ResourceManager.GetString("ExceptionInvalidBamExtendedStepNoStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BAM activity name for directive {0} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidBamInterceptionActivity {
            get {
                return ResourceManager.GetString("ExceptionInvalidBamInterceptionActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAM interception after-map step extension names for directive {0} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidBamInterceptionAfterMapStepExtensionName {
            get {
                return ResourceManager.GetString("ExceptionInvalidBamInterceptionAfterMapStepExtensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post-transformation BAM interception step name for directive {0} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidBamInterceptionPostTransformationStepName {
            get {
                return ResourceManager.GetString("ExceptionInvalidBamInterceptionPostTransformationStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAM interception step extension names for directive {0} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidBamInterceptionStepExtensionName {
            get {
                return ResourceManager.GetString("ExceptionInvalidBamInterceptionStepExtensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BAM interception step name for directive {0} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidBamInterceptionStepName {
            get {
                return ResourceManager.GetString("ExceptionInvalidBamInterceptionStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BAM step name for {0} {1}..
        /// </summary>
        internal static string ExceptionInvalidBamStep {
            get {
                return ResourceManager.GetString("ExceptionInvalidBamStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BAM trackpoint policy name for directive {0} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidBamTrackpointPolicyName {
            get {
                return ResourceManager.GetString("ExceptionInvalidBamTrackpointPolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BAM trackpoint policy version for directive {0} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidBamTrackpointPolicyVersion {
            get {
                return ResourceManager.GetString("ExceptionInvalidBamTrackpointPolicyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BizTalk property name for directive {0} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidBizTalkPropertyName {
            get {
                return ResourceManager.GetString("ExceptionInvalidBizTalkPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BizTalk property namespace for directive {0} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidBizTalkPropertyNamespace {
            get {
                return ResourceManager.GetString("ExceptionInvalidBizTalkPropertyNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BizTalk property value for directive {0} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidBizTalkPropertyValue {
            get {
                return ResourceManager.GetString("ExceptionInvalidBizTalkPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BAM data extraction item name for the {0} step in {1}..
        /// </summary>
        internal static string ExceptionInvalidDataExtractionItemName {
            get {
                return ResourceManager.GetString("ExceptionInvalidDataExtractionItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid directive name for {0} {1}..
        /// </summary>
        internal static string ExceptionInvalidDirective {
            get {
                return ResourceManager.GetString("ExceptionInvalidDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The endpoint for directive {0} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidEndpoint {
            get {
                return ResourceManager.GetString("ExceptionInvalidEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration for directive {0} and endpoint {1} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidEndpointConfiguration {
            get {
                return ResourceManager.GetString("ExceptionInvalidEndpointConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transport for directive {0} and endpoint {1} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidEndpointTransport {
            get {
                return ResourceManager.GetString("ExceptionInvalidEndpointTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BAM extraction information for {0} {1}..
        /// </summary>
        internal static string ExceptionInvalidExtractionInfo {
            get {
                return ResourceManager.GetString("ExceptionInvalidExtractionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BAM continuation prefix for {0} {1}..
        /// </summary>
        internal static string ExceptionInvalidPrefix {
            get {
                return ResourceManager.GetString("ExceptionInvalidPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid property..
        /// </summary>
        internal static string ExceptionInvalidProperty {
            get {
                return ResourceManager.GetString("ExceptionInvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property name for directive {0} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidPropertyName {
            get {
                return ResourceManager.GetString("ExceptionInvalidPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property value for directive {0} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidPropertyValue {
            get {
                return ResourceManager.GetString("ExceptionInvalidPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BAM reference name for the {0} step in {1}..
        /// </summary>
        internal static string ExceptionInvalidReferenceName {
            get {
                return ResourceManager.GetString("ExceptionInvalidReferenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BAM reference type for the {0} step in {1}..
        /// </summary>
        internal static string ExceptionInvalidReferenceType {
            get {
                return ResourceManager.GetString("ExceptionInvalidReferenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BAM related activity name for the {0} step in {1}..
        /// </summary>
        internal static string ExceptionInvalidRelatedActivityName {
            get {
                return ResourceManager.GetString("ExceptionInvalidRelatedActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SOAP action for directive {0} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidSoapAction {
            get {
                return ResourceManager.GetString("ExceptionInvalidSoapAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transformation map for directive {0} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidTransformationMap {
            get {
                return ResourceManager.GetString("ExceptionInvalidTransformationMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validation policy name for directive {0} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidValidationPolicyName {
            get {
                return ResourceManager.GetString("ExceptionInvalidValidationPolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validation policy version for directive {0} cannot be null, empty or whitespace..
        /// </summary>
        internal static string ExceptionInvalidValidationPolicyVersion {
            get {
                return ResourceManager.GetString("ExceptionInvalidValidationPolicyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode a single transformation (BizTalk map) only.   Use multiple directives for multiple transformations..
        /// </summary>
        internal static string ExceptionMapToApply {
            get {
                return ResourceManager.GetString("ExceptionMapToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method or operation is not implemented..
        /// </summary>
        internal static string ExceptionNotImplemented {
            get {
                return ResourceManager.GetString("ExceptionNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML reader passed to the {0} method is null..
        /// </summary>
        internal static string ExceptionReaderIsNull {
            get {
                return ResourceManager.GetString("ExceptionReaderIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode a single retry count only.   Use multiple directives for multiple retry counts..
        /// </summary>
        internal static string ExceptionRetryCount {
            get {
                return ResourceManager.GetString("ExceptionRetryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode a single retry interval only.   Use multiple directives for multiple retry intervals..
        /// </summary>
        internal static string ExceptionRetryInterval {
            get {
                return ResourceManager.GetString("ExceptionRetryInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode a single retry level only.   Use multiple directives for multiple retry levels..
        /// </summary>
        internal static string ExceptionRetryLevel {
            get {
                return ResourceManager.GetString("ExceptionRetryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find XSD schema in assembly resources..
        /// </summary>
        internal static string ExceptionSchemaResourceNotFound {
            get {
                return ResourceManager.GetString("ExceptionSchemaResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML schema set passed to the {0} method is null..
        /// </summary>
        internal static string ExceptionSchemaSetIsNull {
            get {
                return ResourceManager.GetString("ExceptionSchemaSetIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be serialized.   See inner exception..
        /// </summary>
        internal static string ExceptionSerialization {
            get {
                return ResourceManager.GetString("ExceptionSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode a single service window start time only.   Use multiple directives for multiple service windows..
        /// </summary>
        internal static string ExceptionServiceWindowStartTime {
            get {
                return ResourceManager.GetString("ExceptionServiceWindowStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode a single SOAP Action only.   Use multiple directives for multiple endpoints..
        /// </summary>
        internal static string ExceptionSoapAction {
            get {
                return ResourceManager.GetString("ExceptionSoapAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SOAP Action set in directive {0} is an invalid URI.\r\n.
        /// </summary>
        internal static string ExceptionSoapActionInvalidUri {
            get {
                return ResourceManager.GetString("ExceptionSoapActionInvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode a single transport type only.   Use multiple directives for multiple endpoints..
        /// </summary>
        internal static string ExceptionTransportType {
            get {
                return ResourceManager.GetString("ExceptionTransportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred when calling {0}.  See inner exception..
        /// </summary>
        internal static string ExceptionUnexpectedError {
            get {
                return ResourceManager.GetString("ExceptionUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode a single validation policy name only.   Use multiple directives for multiple validation rule sets..
        /// </summary>
        internal static string ExceptionValidationPolicyName {
            get {
                return ResourceManager.GetString("ExceptionValidationPolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} directive can encode a single validation policy version only.   Use multiple directives for multiple validation rule sets..
        /// </summary>
        internal static string ExceptionValidationPolicyVersion {
            get {
                return ResourceManager.GetString("ExceptionValidationPolicyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validation policy version set in directive {0} is an invalid version specifier.\r\n.
        /// </summary>
        internal static string ExceptionValidationPolicyVersionInvalid {
            get {
                return ResourceManager.GetString("ExceptionValidationPolicyVersionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null..
        /// </summary>
        internal static string ExceptionValueIsNull {
            get {
                return ResourceManager.GetString("ExceptionValueIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML writer passed to the {0} method is null..
        /// </summary>
        internal static string ExceptionWriterIsNull {
            get {
                return ResourceManager.GetString("ExceptionWriterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DictionaryType.
        /// </summary>
        internal static string QNameDictionaryType {
            get {
                return ResourceManager.GetString("QNameDictionaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectivesDictionaryType.
        /// </summary>
        internal static string QNameDirectiveDictionaryType {
            get {
                return ResourceManager.GetString("QNameDirectiveDictionaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParametersType.
        /// </summary>
        internal static string QNameParameterType {
            get {
                return ResourceManager.GetString("QNameParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolidsoftReply.Esb.Libraries.Facts.Dictionaries.Resources.BtsPropertiesSchema.xsd.
        /// </summary>
        internal static string XsdBtsPropertiesSchemaFile {
            get {
                return ResourceManager.GetString("XsdBtsPropertiesSchemaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolidsoftReply.Esb.Libraries.Facts.Dictionaries.Resources.DictionarySchema.xsd.
        /// </summary>
        internal static string XsdDictionarySchemaFile {
            get {
                return ResourceManager.GetString("XsdDictionarySchemaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolidsoftReply.Esb.Libraries.Facts.Dictionaries.Resources.DirectivesSchema.xsd.
        /// </summary>
        internal static string XsdDirectiveSchemaFile {
            get {
                return ResourceManager.GetString("XsdDirectiveSchemaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolidsoftReply.Esb.Libraries.Facts.Dictionaries.Resources.DirectivesSchemaProperties.xsd.
        /// </summary>
        internal static string XsdDirectiveSchemaPropertiesFile {
            get {
                return ResourceManager.GetString("XsdDirectiveSchemaPropertiesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolidsoftReply.Esb.Libraries.Facts.Dictionaries.Resources.ParametersSchema.xsd.
        /// </summary>
        internal static string XsdParameterSchemaFile {
            get {
                return ResourceManager.GetString("XsdParameterSchemaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolidsoftReply.Esb.Libraries.Facts.Dictionaries.Resources.PropertiesSchema.xsd.
        /// </summary>
        internal static string XsdPropertiesSchemaFile {
            get {
                return ResourceManager.GetString("XsdPropertiesSchemaFile", resourceCulture);
            }
        }
    }
}
