//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solidsoft.Esb.Test.ESBOnRamp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://solidsoft.com/servicebus/onramp", ConfigurationName="ESBOnRamp.Solidsoft_BizTalk_ESB_OnRamp_OnRampInterface_OnRamp")]
    public interface Solidsoft_BizTalk_ESB_OnRamp_OnRampInterface_OnRamp {
        
        // CODEGEN: Generating message contract since the operation Submit is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Submit", ReplyAction="*")]
        Solidsoft.Esb.Test.ESBOnRamp.SubmitResponse Submit(Solidsoft.Esb.Test.ESBOnRamp.SubmitRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public object part;
        
        public SubmitRequest() {
        }
        
        public SubmitRequest(object part) {
            this.part = part;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public object part;
        
        public SubmitResponse() {
        }
        
        public SubmitResponse(object part) {
            this.part = part;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Solidsoft_BizTalk_ESB_OnRamp_OnRampInterface_OnRampChannel : Solidsoft.Esb.Test.ESBOnRamp.Solidsoft_BizTalk_ESB_OnRamp_OnRampInterface_OnRamp, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Solidsoft_BizTalk_ESB_OnRamp_OnRampInterface_OnRampClient : System.ServiceModel.ClientBase<Solidsoft.Esb.Test.ESBOnRamp.Solidsoft_BizTalk_ESB_OnRamp_OnRampInterface_OnRamp>, Solidsoft.Esb.Test.ESBOnRamp.Solidsoft_BizTalk_ESB_OnRamp_OnRampInterface_OnRamp {
        
        public Solidsoft_BizTalk_ESB_OnRamp_OnRampInterface_OnRampClient() {
        }
        
        public Solidsoft_BizTalk_ESB_OnRamp_OnRampInterface_OnRampClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Solidsoft_BizTalk_ESB_OnRamp_OnRampInterface_OnRampClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Solidsoft_BizTalk_ESB_OnRamp_OnRampInterface_OnRampClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Solidsoft_BizTalk_ESB_OnRamp_OnRampInterface_OnRampClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Solidsoft.Esb.Test.ESBOnRamp.SubmitResponse Solidsoft.Esb.Test.ESBOnRamp.Solidsoft_BizTalk_ESB_OnRamp_OnRampInterface_OnRamp.Submit(Solidsoft.Esb.Test.ESBOnRamp.SubmitRequest request) {
            return base.Channel.Submit(request);
        }
        
        public void Submit(ref object part) {
            Solidsoft.Esb.Test.ESBOnRamp.SubmitRequest inValue = new Solidsoft.Esb.Test.ESBOnRamp.SubmitRequest();
            inValue.part = part;
            Solidsoft.Esb.Test.ESBOnRamp.SubmitResponse retVal = ((Solidsoft.Esb.Test.ESBOnRamp.Solidsoft_BizTalk_ESB_OnRamp_OnRampInterface_OnRamp)(this)).Submit(inValue);
            part = retVal.part;
        }
    }
}
